kind: pipeline
name: kdm-ci
type: docker

platform:
  os: linux
  arch: amd64

node:
  instance: agent-amd64

steps:
  - name: "merge-kdm"
    image: cnrancher/gc-kdm-generator:v0.1.1
  - name: "check-updates"
    image: "alpine/git:2.36.3"
    commands:
      - if [ -n "$(git status --porcelain --untracked-files=no)" ]; then echo "Git is dirty"; git status; exit 1; fi
  - name: "publish"
    image: "orstar/ossutil:v1.7.13-confd"
    environment:
      ENDPOINT:
        from_secret: "endpoint"
      ACCESS_KEY_ID:
        from_secret: "aliyun_access_id"
      ACCESS_KEY_SECRET:
        from_secret: "aliyun_access_secret"
    commands:
      - /entrypoint.sh ossutil cp ./data/data.json oss://pandaria-releases/kontainer-driver-metadata/${DRONE_BRANCH}/data.json
    when:
      event:
        - push
